language: node_js
node_js:
- 'lts/*'
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: TX6oJReAjdrBRMQA63GzwQLPLorWPdaSkutjG63bJnMqTOC2ZqSRyY3i6PptiWyKOv1xkerqe1cugiObaVs/JY3s8RFnwEmuaOuCIkyuYZiEemm0pcm4fmHKgUQ4J5uHVnyoevjAJgcjHvuOwA7iKIPoz719QJYhpNK4NrO1olM=
  on:
    tags: true
    repo: noflo/noflo-docco
